set_load 5.000 [all_outputs]
set_property LOAD 5 [get_ports {output_data[0]}]
set_property LOAD 5 [get_ports {output_data[10]}]
set_property LOAD 5 [get_ports {output_data[11]}]
set_property LOAD 5 [get_ports {output_data[12]}]
set_property LOAD 5 [get_ports {output_data[13]}]
set_property LOAD 5 [get_ports {output_data[14]}]
set_property LOAD 5 [get_ports {output_data[15]}]
set_property LOAD 5 [get_ports {output_data[1]}]
set_property LOAD 5 [get_ports {output_data[2]}]
set_property LOAD 5 [get_ports {output_data[3]}]
set_property LOAD 5 [get_ports {output_data[4]}]
set_property LOAD 5 [get_ports {output_data[5]}]
set_property LOAD 5 [get_ports {output_data[6]}]
set_property LOAD 5 [get_ports {output_data[7]}]
set_property LOAD 5 [get_ports {output_data[8]}]
set_property LOAD 5 [get_ports {output_data[9]}]
set_property LOAD 5 [get_ports output_valid]
